apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-doll
  annotations:
    github.com/project-slug: arivukaran/silver-doll
 links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
spec:
  type: other
  lifecycle: unknown
  owner: arivukaran

